stages:
    - build
    - deploy
image: docker:20.10.5
services:
    - docker:20.10.5-dind
builder:
    stage: build
    tags:
        - linux
    script:
        - docker build -t some_local_build:latest .
deployer:
    stage: deploy
    tags:
        - linux
    script:
        - docker build -t muroway-instance.gitlab.yandexcloud.net:5050/ols/my-awesome-project-for-netology/hello:gitlab-$CI_COMMIT_SHORT_SHA .
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push muroway-instance.gitlab.yandexcloud.net:5050/ols/my-awesome-project-for-netology/hello:gitlab-$CI_COMMIT_SHORT_SHA