---
  - name: CLICKHOUSE | Install Clickhouse
    hosts: clickhouse
    roles:
      - clickhouse
    ignore_errors: true
  - name: LIGHTHOUSE | Install Lighthouse
    hosts: lighthouse
    roles:
      - lighthouse
  - name: VECTOR | Install Vector
    hosts: vector
    roles:
      - vector