---
  - name: CLICKHOUSE | Install Clickhouse
    hosts: clickhouse
    roles:
      - clickhouse
  - name: LIGHTHOUSE | Install Lighthouse
    host: lighthouse
    roles:
      - lighthouse
  - name: VECTOR | Install Vector
    host: Vector
    roles:
      - vector