---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.69.11
    jenkins-agent-01:
      ansible_host: 158.160.71.79
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
            jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: ols
