---
#Обьеденить с site.yml
- name: Try run Vector
  hosts: all
  tasks:
    - name: Get RPM
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.34.0/vector-0.34.0-1.x86_64.rpm"
        dest: "./vector.rpm"
    - name: Install vector package
      become: true
      become_method: su #ошибка при дефолтном методе, отсутствует sudo (sudo: command not found)
      ansible.builtin.yum:
        name:
          - vector.rpm
    - name: Get Vector version
      ansible.builtin.command: vector --version
      register: is_installed
