---
#Обьеденить с site.yml
- name: Try run Vector
  hosts: all
  tasks:
    - name: Get Vector version
      ansible.builtin.command: vector --version
      register: is_installed
    - name: Get RPM
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.34.0/vector-0.34.0-1.x86_64.rpm"
        dest: "{{ansible_user_dir}}/vector.rpm"
        mode: 0755
        when:
          - is_installed is failed
          - ansible_distribution == "vector-01"
