---
  vector_config:
    sources: 
      sample_file:
        type: file
        read_from: beginning
        ignore_older_secs: 600
          include:
            - /home/ols/logs/**/*.log
    sinks:
      to_clickhouse:
        type: clickhouse
        inputs:
          - sample_file
        endpoint: {{ clickhouse-01 }}:8123 #вставить ip clickhouse-01
        databases: logs
        table: my_table
        skip_unknown_fields: true
        compression: gzip